global:
  scrape_interval: 15s
  evaluation_interval: 15s

# kubectl patch ds monitoring-prometheus-node-exporter --type "json" -p "[{\"op\": \"remove\", \"path\" : \"/spec/template/spec/containers/0/volumeMounts/2/mountPropagation\"}]"

prometheus:
  alertmanager:
    enabled: false
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus.yml:
    scrape_configs:
      - job_name: 'node'
        static_configs:
          - targets: ['localhost:9100']
grafana:
  service:
    type: NodePort
  persistence:
    enabled: true
    type: pvc
    size: 1Gi
