apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - image: faemeister/nest-todo_api:latest
          name: nest-todo-api
          env:
            - name: 'API_HTTP_PORT'
              value: '3000'
            - name: 'PROMETHEUS_METRIC_PATH'
              value: '/metrics'
            - name: 'AUTH_SERVICE_HOST'
              value: 'auth-service'
            - name: 'AUTH_SERVICE_PORT'
              value: '50051'
            - name: 'CANVA_SERVICE_HOST'
              value: 'canva'
            - name: 'CANVA_SERVICE_PORT'
              value: '50051'
            - name: 'TODO_SERVICE_HOST'
              value: 'todo'
            - name: 'TODO_SERVICE_PORT'
              value: '50051'
